import type { ReviewCommentsLabels } from './types';

/** Default English UI strings (override via ReviewCommentsProvider `labels` prop). */
export const defaultReviewCommentsLabels: ReviewCommentsLabels = {
  newThreadTitle: 'Add comment on selected text',
  authorPlaceholder: 'Name (optional)',
  commentPlaceholder: 'Write your comment',
  replyPlaceholder: 'Reply to this thread',
  addThread: 'Add thread',
  postComment: 'Post',
  commentButton: 'Comment',
  cancel: 'Cancel',
  submitting: 'Submitting...',
  dbUnavailable:
    'Comments cannot be saved because the review comments database is not connected. For local development, set REVIEW_COMMENTS_MONGODB_URL.',
  submitFailed: 'Could not save. Try again.',
  moreActions: 'More actions',
  editComment: 'Edit comment',
  deleteComment: 'Delete comment',
  confirmDeleteComment: 'Delete this comment?',
  today: 'Today',
  commentTime: ({ time, dateLabel }) => `${time} · ${dateLabel}`,
  threadPanelTitle: 'Comments',
  noThreads: 'No comments yet',
  open: 'Open',
  resolved: 'Resolved',
  reply: 'Reply',
  resolve: 'Resolve',
  reopen: 'Reopen',
  viewResolvedToggle: () => 'View resolved',
  hideResolvedToggle: 'Hide resolved',
  noOpenThreads: 'No open comments on this page.',
  noResolvedThreads: 'No resolved comments yet.',
  loadingComments: 'Loading comments...',
  hiddenCommentsCount: ({ count }) =>
    count === 1 ? 'Show 1 more comment' : `Show ${count} more comments`,
  showMore: 'More',
  showLess: 'Less',
  commentingAs: 'Commenting as',
  saveName: 'Save',
  prOverviewTitle: 'Comments',
  panelSectionNavigate: 'Navigate',
  panelSectionPages: 'Pages with comments',
  showPagesList: 'Show pages',
  hidePagesList: 'Hide pages',
  addComment: 'Add comment',
  emptyPanelHint:
    'Highlight text on the page, then click Add comment next to your selection. The comment box opens here.',
  totalCommentsBadge: ({ count }) => `${count} comments`,
  unreadBadge: ({ count }) => `${count} unread`,
  progressLabel: ({ current, total }) => `${current} of ${total} pages`,
  previousPage: 'Previous page',
  nextPage: 'Next page',
  threadCount: ({ count }) => `${count} threads`,
  unreadThreadCount: ({ count }) => `${count} unread`,
  collapse: 'Collapse',
  collapsedBadge: ({ count }) => `${count} comments`,
  collapsedUnreadBadge: ({ unread, total }) => `${unread} unread / ${total} comments`,
  commentingAsCompact: ({ author }) => `As: ${author}`,
  show: 'Show',
  hide: 'Hide',
  newCommentBadge: 'New',
  copyThreadsAsMarkdown: 'Copy threads as Markdown',
  copyThreadsAsMarkdownDone: 'Copied',
};
